services:
  frontend:
    image: eco-ui:0.0.3
    container_name: ui
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier

  backend:
    image: eco-server:0.0.3
    container_name: server
    networks:
      - back-tier

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'eco_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33060:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}