services:
  frontend:
    image: eco-ui:0.0.5
    container_name: ui
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier

  backend:
    image: eco-server:0.0.6
    container_name: server
    networks:
      - back-tier

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'eco_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - back-tier
volumes:
  my-db:

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}